#!/bin/bash

# Copyright 2015 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Notes:
#  - Please install "jq" package before using this driver.

usage() {
	err "Invalid usage. Usage: "
	err "\t$0 init"
	err "\t$0 mountdevice <mount dir> <mount device> <json params>"
	err "\t$0 unmountdevice <mount dir>"
	exit 1
}

err() {
	echo -ne $* 1>&2
}

log() {
	echo -ne $* >&1
}

domount() {
	MNTPATH=$1
	SHARE=$(echo $2 | jq -r '.share')
	FILE=$(echo $2 | jq -r '.file')
	FSTYPE=$(echo $2 | jq -r '.["kubernetes.io/fsType"]')
	MMP=$(echo $2 | jq -r '.mmp')
	SIZE=$(echo $2 | jq -r '.size' | tr '[:lower:]' '[:upper:]')
	FSCK=$(echo $2 | jq -r '.fsck')

	if [ "${SHARE}" != "null" ]; then
		if ! mountpoint -q "${SHARE}"; then
			err "{ \"status\": \"Failed\", \"message\": \"${SHARE} is not mounted\"}"
			exit 0
		fi
		FILE="${SHARE}/${FILE}"
	fi

    if [[ "${MMP}" != +(false|no|0) ]] && [ "${FSTYPE}" == "ext4" ]; then
		MMP_INTERVAL=$(echo $3 | jq -r '.mmpUpdateInterval')
		[ "${MMP_INTERVAL}" == "null" ] && MMP_INTERVAL=5
		MMP_OPT="-O mmp -E mmp_update_interval=${MMP_INTERVAL}"
	fi

	if [ ! -f "${FILE}" ]; then
	    if [ -z "${SIZE}" ]; then
		err "{\"status\": \"Failure\", \"message\": \"${FILE} does not exist\"}"
		exit 1
            else
                mkdir -p "$(dirname "${FILE}")"
                truncate -s ${SIZE} "${FILE}"
            fi
	fi

	if mountpoint -q "${MNTPATH}"; then
		log "{\"status\": \"Success\"}"
		exit 0
	fi

	VOLFSTYPE=`blkid -o udev ${FILE} 2>/dev/null|grep "ID_FS_TYPE"|cut -d"=" -f2`
	if [ "${VOLFSTYPE}" == "" ]; then

		mkfs -t ${FSTYPE} ${MMP_OPT} ${FILE} >/dev/null 2>&1
		if [ $? -ne 0 ]; then
			err "{ \"status\": \"Failure\", \"message\": \"Failed to create fs ${FSTYPE} on device ${FILE}\"}"
			exit 1
		fi
	fi

	mkdir -p "${MNTPATH}" &> /dev/null

    modprobe nbd 2> /dev/null
	if [ $? -ne 0 ]; then
		err "{ \"status\": \"Failure\", \"message\": \"Failed to load nbd module\"}"
		exit 1
	fi

    NBDNUMBERS="$(ls -1 /dev/nbd[0-9]* | grep -o [0-9]* | sort -h)"
    for i in $NBDNUMBERS; do
        if fdisk -l "/dev/nbd$i" 2>&1 | grep -q 'Inappropriate ioctl for device'; then

            NBDDEVICE="/dev/nbd$i"
            echo "${NBDDEVICE}" > "${MNTPATH}.device"
            qemu-nbd -f raw -c "${NBDDEVICE}" "${FILE}" &>/dev/null

	        if [ $? -ne 0 ]; then
                continue
	        fi

            break
        fi
    done

    if [ $? -ne 0 ]; then
        err "{ \"status\": \"Failure\", \"message\": \"Failed to setup nbd device from ${FILE}\"}"
        exit 1
    fi

    if [ -z "${NBDDEVICE}" ]; then
		err "{\"status\": \"Failure\", \"message\": \"Free nbd device was not found\"}"
		exit 1
    fi

    case "${FSCK}" in
        false|no|0  )   true ;;
        fix_all     )   fsck -y -t ${FSTYPE} ${NBDDEVICE} &> /dev/null ;;
        force       )   fsck -f -t ${FSTYPE} ${NBDDEVICE} &> /dev/null ;;
        *           )   fsck -n -t ${FSTYPE} ${NBDDEVICE} &> /dev/null ;;
    esac

    if [ $? -ne 0 ]; then
        err "{ \"status\": \"Failure\", \"message\": \"Fsck check for ${NBDDEVICE} from ${FILE} was failed\"}"
        qemu-nbd -d "${NBDDEVICE}" &>/dev/null
        exit 1
    fi

	mount "${NBDDEVICE}" "${MNTPATH}" &> /dev/null
	if [ $? -ne 0 ]; then
		err "{ \"status\": \"Failure\", \"message\": \"Failed to mount device ${NBDDEVICE} from ${FILE} at ${MNTPATH}\"}"
        qemu-nbd -d "${NBDDEVICE}" &>/dev/null
		exit 1
	fi

	log "{\"status\": \"Success\"}"
	exit 0
}

unmount() {
	MNTPATH=$1
	if [ -d ${MNTPATH} ] && mountpoint -q "${MNTPATH}"; then
	    umount ${MNTPATH} &> /dev/null
	    if [ $? -ne 0 ]; then
	        err "{ \"status\": \"Failed\", \"message\": \"Failed to unmount volume at ${MNTPATH}\"}"
	        exit 1
	    fi
    fi

    if [ -f ${MNTPATH}.device ]; then
        qemu-nbd -d "$(cat ${MNTPATH}.device)" &>/dev/null
        rm -f ${MNTPATH}.device
    fi

	log "{\"status\": \"Success\"}"

	exit 0
}

op=$1

if ! command -v jq >/dev/null 2>&1; then
	err "{ \"status\": \"Failure\", \"message\": \"'jq' binary not found. Please install jq package before using this driver\"}"
	exit 1
fi

if [ "$op" = "init" ]; then
        log '{"status": "Success", "capabilities": {"attach": false}}'
	exit 0
fi

if [ $# -lt 2 ]; then
	usage
fi

shift

case "$op" in
	mount)
		domount $*
		;;
	unmount)
		unmount $*
		;;
	*)
		log "{ \"status\": \"Not supported\" }"
		exit 0
esac

exit 1
