#!/bin/sh
# Copyright 2015 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

usage() {
    cat 1>&2 <<EOF

Invalid usage. Usage: 
    $DRIVER init
    $DRIVER waitforattach <json params>
    $DRIVER mountdevice <mount dir> <mount device> <json params>
    $DRIVER unmountdevice <mount dir>

EOF
    exit 1
}

err() {
    printf "$*" 1>&2
}

log() {
    printf "$*" >&1
}

getdevice() {
    # Find and connect new nbd device
    if [ -z "${NBDDEVICE}" ]; then
        local NBDNUMBERS="$(ls -1 /dev/nbd[0-9]* | grep -o [0-9]* | sort -h)"
        for i in $NBDNUMBERS; do
            if lsblk "/dev/nbd$i" 1>/dev/null 2>/dev/null && mkfifo /run/lock/qemu-nbd-nbd$i 2> /dev/null; then
                local NBDDEVICE="/dev/nbd$i"
                break
            fi
        done
    fi
    echo "$NBDDEVICE"
}

dofilesystem() {
    [ "$FSTYPE" = "" ] && FSTYPE="ext4"
    [ "$MMP_INTERVAL" = null ] && MMP_INTERVAL=5 
    [ "$FSCK_OPTIONS" = null ] && FSCK_OPTIONS="a"

    # Calculate multimount protection options
    case "$MMP" in false|no|0)
        if [ "${FSTYPE}" = "ext4" ]; then
            MMP_OPT="-O mmp -E mmp_update_interval=${MMP_INTERVAL}"
        fi
    ;; esac

    VOLFSTYPE=`blkid -o udev "$1" 2>/dev/null|grep "ID_FS_TYPE"|cut -d"=" -f2`
    if [ "${VOLFSTYPE}" = "" ]; then
        # Make filesystem
        mkfs -t "${FSTYPE}" ${MMP_OPT} "${1}" >/dev/null 2>&1
        if [ $? -ne 0 ]; then
            err "{ \"status\": \"Failure\", \"message\": \"Failed to create fs ${FSTYPE} on device ${1}\"}"
            exit 1
        fi
    else
        # Do filesystem check
        case "$FSCK" in false|no|0)
            fsck -${FSCK_OPTIONS} ${1} 1>/dev/null 2>/dev/null
            if [ $? -ne 0 ]; then
                err "{ \"status\": \"Failure\", \"message\": \"Fsck -${FSCK_OPTIONS} check for ${1} was failed\"}"
                exit 1
            fi
        ;; esac
    fi
} 

waitforattach() {
    FSTYPE=$(echo "$1" | jq -r '.["kubernetes.io/fsType"]')
    MMP=$(echo "$1" | jq -r '.mmp')
    SIZE=$(echo "$1" | jq -r '.size' | tr '[:lower:]' '[:upper:]')
    FSCK=$(echo "$1" | jq -r '.fsck')
    MMP_INTERVAL=$(echo "$1" | jq -r '.mmpUpdateInterval')
    FSCK_OPTIONS=$(echo "$1" | jq -r '.fsckOptions')
    ALLOCATE=$(echo "$1" | jq -r '.allocate')

    # Get driver specific options
    if [ "$DRIVER" = "sheepdog" ]; then
        for OPTION in prealloc hyper copies address port block_size_shift; do
            VALUE="$(echo "$2" | jq -r ".$OPTION")"
            export "$(echo $OPTION | tr '[:lower:]' '[:upper:]')=$VALUE"
            if [ "$VALUE" != "null" ]; then
                export DOG_CREATE_OPTS+=" --${OPTION}=${VALUE}"
            fi
        done
        VDINAME=$(echo $2 | jq -r '.vdiname')
    else
        SHARE=$(echo "$1" | jq -r '.share')
        FILE=$(echo "$1" | jq -r '.file')
        if [ "${SHARE}" != "null" ]; then
            FILE="${SHARE}/${FILE}"
        fi
    fi

    if [ "$DRIVER" != "sheepdog" ]; then
        IMAGE_URL="$FILE"
    elif [ "$ADDRESS" != null ] && [ "$PORT" == null ]; then
        IMAGE_URL="sheepdog://${ADDRESS}/${VDINAME}"
    elif [ "$ADDRESS" != null ] && [ "$PORT" != null ]; then
        IMAGE_URL="sheepdog://${ADDRESS}:${PORT}/${VDINAME}"
    elif [ "$ADDRESS" == null ] && [ "$PORT" != null ]; then
        IMAGE_URL="sheepdog://:${PORT}/${VDINAME}"
    else
        IMAGE_URL="sheepdog:${VDINAME}"
    fi

    # Check is SHARE mountpoint
    if [ "$DRIVER" != "sheepdog" ] && [ "${SHARE}" != "null" ]; then
        if ! mountpoint -q "${SHARE}"; then
            err "{ \"status\": \"Failed\", \"message\": \"${SHARE} is not mounted\"}"
            exit 0
        fi
    fi

    # Check is image exist
    if [ "$DRIVER" != "sheepdog" ]; then
        if [ ! -f "${FILE}" ]; then
            IMAGE_EXIST=0
        else
            IMAGE_EXIST=1
        fi
    else
        QEMU_IMG_INFO_STDERR="$(qemu-img info "${IMAGE_URL}" 2>&1 1>/dev/null)"
        if echo "$QEMU_IMG_INFO_STDERR" | grep -q 'No vdi found'; then
            IMAGE_EXIST=0
        elif [ -n "$QEMU_IMG_INFO_STDERR" ]; then
            err "{ \"status\": \"Failure\", \"message\": \"${QEMU_IMG_INFO_STDERR}\"}"
            exit 1
        fi
        IMAGE_EXIST=1
    fi

    # Allocate image
    if [ "$IMAGE_EXIST" = 0 ]; then
        if [ -z "${SIZE}" ]; then
            err "{\"status\": \"Failure\", \"message\": \"${IMAGE_URL} does not exist\"}"
            exit 1
        fi

        if [ "$DRIVER" != "sheepdog" ]; then
            mkdir -p "$(dirname "${FILE}")"
            truncate -s ${SIZE} "${FILE}"
            if [ $? -ne 0 ]; then
                err "{\"status\": \"Failure\", \"message\": \"Can not create file ${FILE}\"}"
                exit 1
            fi
        else
            dog vdi create $DOG_CREATE_OPTS "$VDINAME" "$SIZE"
            if [ $? -ne 0 ]; then
                err "{ \"status\": \"Failure\", \"message\": \"Failed to create vdi ${IMAGE_URL}\"}"
                exit 1
            fi
        fi
    fi

    # Do filesystem check
    if [ "$DRIVER" != "sheepdog" ]; then
        dofilesystem "$FILE"
    fi

    # Skip device setting when loop
    if [ "$DRIVER" = "loop" ]; then
        log "{\"status\": \"Success\", \"device\":\"${FILE}\"}"
        exit 0
    fi

    # Check for qemu binaries
    for binary in qemu-nbd qemu-img; do
        if ! command -v $binary >/dev/null 2>&1; then
            err "{ \"status\": \"Failure\", \"message\": \"'$binary' binary not found. Please install qemu-utils package before using this driver\"}"
            exit 1
        fi
    done

    # Load nbd module
    modprobe nbd 2> /dev/null
    if [ $? -ne 0 ]; then
        err "{ \"status\": \"Failure\", \"message\": \"Failed to load nbd module\"}"
        exit 1
    fi

    # Check is already attached
    NBDDEVICE="$(ps aux | sed -n "s|.*qemu-nbd -f raw -c \(/dev/nbd[0-9]\+\) ${IMAGE_URL}\$|\1|p" | head -n1)"
    if [ ! -z "${NBDDEVICE}" ]; then
        log "{\"status\": \"Success\", \"device\":\"${NBDDEVICE}\"}"
        exit 0
    fi

    # Get free nbd device
    NBDDEVICE="$(getdevice)"
    if [ -z "${NBDDEVICE}" ]; then
        err "{\"status\": \"Failure\", \"message\": \"Free nbd device was not found\"}"
        exit 1
    fi

    # Setup nbd device
    qemu-nbd -f raw -c "${NBDDEVICE}" "${IMAGE_URL}" 1>/dev/null 2>/dev/null
    if [ $? -ne 0 ]; then
        err "{ \"status\": \"Failure\", \"message\": \"Failed to setup nbd device "${NBDDEVICE}" from ${FILE}\"}"
        exit 1
    fi

    # Do filesystem check
    if [ "$DRIVER" = "sheepdog" ]; then
        dofilesystem "$NBDDEVICE"
    fi

    log "{\"status\": \"Success\", \"device\":\"${NBDDEVICE}\"}"
    exit 0
}

mountdevice() {
    MNTPATH=$1
    DEVICE=$2
    MOUNT_OPTIONS=$(echo $3 | jq -r '.mount_options')
    [ "$MOUNT_OPTIONS" = null ] && MOUNT_OPTIONS=""
    if [ "$DRIVER" = "loop" ]; then
        MOUNT_OPTIONS="loop,$MOUNTOPTIONS"
    fi

    # Create mountpoint
    mkdir -p "${MNTPATH}" 1>/dev/null 2>/dev/null

    # Check is already mounted
    if mountpoint -q "${MNTPATH}"; then
        log "{\"status\": \"Success\"}"
        exit 0
    fi

    # Mount device
    mount -o "${MOUNT_OPTIONS}" "${DEVICE}" "${MNTPATH}" 1>/dev/null 2>/dev/null
    if [ $? -ne 0 ]; then
        err "{ \"status\": \"Failure\", \"message\": \"Failed to mount device ${DEVICE} at ${MNTPATH}\"}"
        exit 1
    fi

    log "{\"status\": \"Success\"}"
    exit 0
}


unmountdevice() {
    MNTPATH=$1
    DEVICE=$(mount | awk "\$3 == \"$(readlink -f $MNTPATH)\" {print \$1}" | head -n 1)

    if [ ! -d ${MNTPATH} ]; then
        log "{\"status\": \"Success\"}"
        exit 0
    fi

    if ! mountpoint -q "${MNTPATH}"; then
        log "{\"status\": \"Success\"}"
        exit 0
    fi

    umount ${MNTPATH} 1>/dev/null 2>/dev/null
    if [ $? -ne 0 ]; then
        err "{ \"status\": \"Failed\", \"message\": \"Failed to unmount volume at ${MNTPATH}\"}"
        exit 1
    fi

    if [ "$DRIVER" != "loop" ]; then
        sleep 1
        qemu-nbd -d ${DEVICE} 1>/dev/null 2>/dev/null
        if [ $? -ne 0 ]; then
            err "{ \"status\": \"Failure\", \"message\": \"Failed to detach device ${DEVICE}\"}"
            exit 1
        fi
    fi

    log "{\"status\": \"Success\"}"
    exit 0
}


PATH="$PATH:$(dirname "$(readlink -f "$0")")"
DRIVER="$(basename $0)"
OPERATION=$1

# enable debug
#echo "$DRIVER $@" >> /tmp/flex-qemu-nbd.log

case "${DRIVER}" in
    loop|qemu-nbd|nbd|sheepdog)
        true
        ;;
    *)
        err "{ \"status\": \"Failure\", \"message\": \"'${DRIVER}' wrong name for driver\"}"
        exit 1
        ;;
esac

if ! command -v jq >/dev/null 2>&1; then
    err "{ \"status\": \"Failure\", \"message\": \"'jq' binary not found. Please install jq package before using this driver\"}"
    exit 1
fi

if [ "$OPERATION" = "init" ]; then
    log "{\"status\":\"Success\",\"capabilities\":{\"attach\":true}}"
    exit 0
fi

if [ $# -lt 2 ]; then
    usage
fi

shift

case "$OPERATION" in
    waitforattach)
        waitforattach $*
        ;;
    mountdevice)
        mountdevice $*
        ;;
    unmountdevice)
        unmountdevice $*
        ;;
    *)
        log "{ \"status\": \"Not supported\" }"
        exit 0
    ;;
esac

exit 1
